services:
  postgres:
    image: postgres:17
    container_name: psql-habit
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: habit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_habit:/var/lib/postgresql/data

volumes:
  postgres_data_habit:
